stages:
  - deploy

variables:
  #set these in Settings > CI/CD Settings > Variables 
  DID_S3_BUCKET_US_E1: "s3://opalapp-opal-dev-use1-ap-fortifidstaticassetsbuck-fcko7emh9u2i/build/directid/"
  DID_S3_BUCKET_US_W1: "s3://opalapp-opal-dev-usw1-ap-fortifidstaticassetsbuck-kgbssmqm2man/build/directid/"
  DID_S3_BUCKET_US_W2: "s3://fortifid-opalv2-dev-usw2-fortifidstaticassetsbuck-45sqjyoln3uf/build/directid/"

deploy_production:
  #image: python:latest
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest 
  stage: deploy
  tags:
    - did-service
  when: manual
  script:
    #- pip install awscli
    - mkdir ./.tmp
    - tar --exclude='.[^/]*' -czvf ./.tmp/didservice.tar.gz .
    - aws s3 cp ./.tmp/didservice.tar.gz $DID_S3_BUCKET_US_W1 --sse AES256
    - aws s3 cp ./data/install.sh $DID_S3_BUCKET_US_W1 --sse AES256
    - aws s3 cp ./.tmp/didservice.tar.gz $DID_S3_BUCKET_US_W2 --sse AES256
    - aws s3 cp ./data/install.sh $DID_S3_BUCKET_US_W2 --sse AES256
    - aws s3 cp ./.tmp/didservice.tar.gz $DID_S3_BUCKET_US_E1 --sse AES256
    - aws s3 cp ./data/install.sh $DID_S3_BUCKET_US_E1 --sse AES256
  only:
  - master
  #No need for artifacts.
  #artifacts:
    #name: "DID-Release-$CI_COMMIT_SHORT_SHA"
    #paths:
      #- ./.tmp/didservice.tar.gz
