stages:
  - deploy

variables:
  S3_BUCKET_NAME: "barb-dev"
deploy_production:
  image: python:latest
  stage: deploy
  when: manual
  script:
    - pip install awscli
    - mkdir ./.tmp
    - tar --exclude='.[^/]*' -czvf ./.tmp/didservice-master.tar.gz .
    - aws s3 cp ./.tmp/didservice-master.tar.gz s3://$S3_BUCKET_NAME/latest/
  only:
  - master
