stages:
  - deploy

variables:
  #set these in Settings > CI/CD Settings > Variables 
  #REGION: "us-west-1"
  #DID_S3_BUCKET: "s3://barb-dev/latest/"

deploy_production:
  image: python:latest
  stage: deploy
  when: manual
  script:
    - pip install awscli
    - mkdir ./.tmp
    - tar --exclude='.[^/]*' -czvf ./.tmp/didservice-master.tar.gz .
    - aws s3 cp ./.tmp/didservice-master.tar.gz $DID_S3_BUCKET --sse AES256
  only:
  - master
