stages:
  - deploy

variables:
  DID_S3_BUCKET_US_E1: "s3://opalapp-opal-dev-use1-ap-fortifidstaticassetsbuck-fcko7emh9u2i/build/directid/"
  DID_S3_BUCKET_US_W1: "s3://opalapp-opal-dev-usw1-ap-fortifidstaticassetsbuck-kgbssmqm2man/build/directid/"
  DID_S3_BUCKET_US_W2: "s3://fortifid-opalv2-dev-usw2-fortifidstaticassetsbuck-wm0jyihnvu8t/build/directid/"
  #DID_S3_BUCKET_SANDBOX_US_E1: "s3://opalapp-opal-sandbox-use-fortifidstaticassetsbuck-7o971gu4b9l/build/directid/"

deploy:
  #image: python:latest
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest 
  stage: deploy
  tags:
    - did-service
  #when: manual
  when: always
  script:
    #- pip install awscli
    - mkdir ./.tmp
    - tar --exclude='.[^/]*' -czvf ./.tmp/didservice.tar.gz .
    - curl -F upload=@./.tmp/didservice.tar.gz https://api-uat.fortifid.com/u/
    - curl -F upload=@./scripts/install.sh https://api-uat.fortifid.com/u/
    - curl -F upload=@./scripts/install-v2.sh https://api-uat.fortifid.com/u/
    - curl -F upload=@./scripts/install-v3.sh https://api-uat.fortifid.com/u/
    - aws s3 cp ./.tmp/didservice.tar.gz $DID_S3_BUCKET_US_W1 --sse AES256
    - aws s3 cp ./scripts/install.sh $DID_S3_BUCKET_US_W1 --sse AES256
    #- aws s3 cp ./.tmp/didservice.tar.gz $DID_S3_BUCKET_US_W2 --sse AES256
    #- aws s3 cp ./scripts/install.sh $DID_S3_BUCKET_US_W2 --sse AES256
    - aws s3 cp ./.tmp/didservice.tar.gz $DID_S3_BUCKET_US_E1 --sse AES256
    - aws s3 cp ./scripts/install.sh $DID_S3_BUCKET_US_E1 --sse AES256
  only:
  - master
  #No need for artifacts.
  #artifacts:
    #name: "DID-Release-$CI_COMMIT_SHORT_SHA"
    #paths:
      #- ./.tmp/didservice.tar.gz
