
# Most of these endpoints will be behind a firewall and only to be called directly from the API gateway.
# We will need to secure them nevertheless.

# Change this to the base url of the did service. 
#@base_url = https://dev.barbarians.com:8999
@base_url = https://api.dev.fortifid.com:8999
#@base_url = http://127.0.0.1:8998

###
# Generate URL for DirectID Connect 
#
# @name income
POST {{base_url}}/directid/generate-income-url
content-type: application/json

{
    "customer_id": "company-123",
    "full_name": "Cisco Caceres",
    "email_address": "cisco801@gmail.com",
    "phone_number": "2066597857",
    "request_id": "{{$guid}}",
    "shorten_url": true     
}

###
# DirectID incoming consent webhook
# After a user authorizes access to their account 

#@transaction_id = {{income.response.body.$.transaction_id}}
#@transaction_id=8b1f82e0-d942-4029-82ba-d0a9e610b76d 
POST {{base_url}}/directid/webhook?key=kPgqykCWhR82ePaU4fWOufpcfSW3VqDrR
content-type: application/json

# For some reason this is not working in some environments.
# < ./data/directid_consent.json
# So inlining it.
{
    "consentId": "{{$guid}}",
    "applicationId": "11e3cccb-5511-4e5f-adb6-e6ec82081f08",
    "customerReference": "{{income.response.body.$.transaction_id}}",
    "providerAuthentication": "Error",
    "dataAvailability": "Complete",
    "paymentConfirmation": null,
    "reauthentication": false,
    "errorMessage": null
}

###
# Get request status
#
GET {{base_url}}/directid/check-request?transaction_id={{income.response.body.$.transaction_id}}
content-type: application/json

###
# Service restart
# This will restart the main DirectID service.
# Later we can have a parameter to restart specific services and
# a reload endpoint to just reload the parameters without restarting the service.
GET {{base_url}}/system/restart

###
# This will update the DID service.
GET {{base_url}}/system/update

################
# Dynamic Code #
################

###
# Submit Code #1 (add)
# Just proof of concept
POST {{base_url}}/directid/code-submit?id=add
content-type: text/plain

'use strict';

return data.a + data.b;

###
# Submit Code #2 (subtract)
# Just proof of concept
POST {{base_url}}/directid/code-submit?id=subtract
content-type: text/plain

'use strict';

return data.a - data.b;

###
# Submit Code #3 (did_1)
POST {{base_url}}/directid/code-submit?id=did_1
content-type: text/plain

'use strict';

const validateInput =()=> {
    //Do validation
}

const summary = data.summary;
const meta = data.meta;

let output;
if(summary) {
    output = {
        estimatedIncome: summary.estimatedIncome,
        confidenceScore: summary.confidenceScore,
        confidenceScoreFlags: {...summary.confidenceScoreFlags},
        requestStartX : 0,
        requestComplete : Date.now(),
        requestDuration: 0
    }
}

if (meta) {
    output = output || {};
    output.requestStart = meta.request_timestamp;
    output.requestDuration = output.requestComplete - output.requestStart;
}

return output;


###
# Run Code #1 (add)
# Just proof of concept
POST {{base_url}}/directid/code-run?id=add
content-type: application/json

{
    "a": 120,
    "b": 50
}

###
# Run Code #2 (subtract)
# Just proof of concept
POST {{base_url}}/directid/code-run?id=subtract
content-type: application/json

{
    "a": 100,
    "b": 50
}

###
# Run Code #3 (did_01)
POST {{base_url}}/directid/code-run?id=did_1
content-type: application/json

{ "summary":
    {
      "month1": {
        "income": 0,
        "month": 1,
        "year": 2020
      },
      "month2": {
        "income": 0,
        "month": 2,
        "year": 2020
      },
      "month3": {
        "income": 0,
        "month": 3,
        "year": 2020
      },
      "month4": {
        "income": 0,
        "month": 4,
        "year": 2020
      },
      "month5": {
        "income": 0,
        "month": 5,
        "year": 2020
      },
      "month6": {
        "income": 0,
        "month": 6,
        "year": 2020
      },
      "month7": {
        "income": 0,
        "month": 7,
        "year": 2020
      },
      "month8": {
        "income": 0,
        "month": 8,
        "year": 2020
      },
      "month9": {
        "income": 0,
        "month": 9,
        "year": 2020
      },
      "month10": {
        "income": 6433.9,
        "month": 10,
        "year": 2020
      },
      "month11": {
        "income": 3216.95,
        "month": 11,
        "year": 2020
      },
      "estimatedIncome": 0,
      "confidenceScore": 7,
      "confidenceScoreFlags": {
        "incomeForLast3Months": false,
        "varianceTolerance5Percent": true,
        "varianceTolerance10Percent": true,
        "mostRecentCheckValue": true,
        "stabilityOverall": 3,
        "stability6Months": 0
      }
    }
}
###
# Get EC2 instance meta for auto-configuration use
GET http://169.254.169.254/latest/dynamic/instance-identity/document
###
# Sample results
{
  "CustomerAccountID": "testcomp",
  "TransactionID": "3c2c15a8-3146-4518-9bf2-dd15819bbaa1",
  "RequesterRef": "b58491d7-9dd2-4581-91b1-26ecb4eb8568",
  "requestComplete": 1610422854896,
  "requestStart": 1610422824192,
  "requestDuration": 30704,
  "apiRequestDuration": 2412,
  "estimatedIncome": 0,
  "confidenceScore": 7,
  "confidenceScoreFlags": {
    "incomeForLast3Months": false,
    "varianceTolerance5Percent": true,
    "varianceTolerance10Percent": true,
    "mostRecentCheckValue": true,
    "stabilityOverall": 3,
    "stability6Months": 0
  },
  "status": "incomeDirectIDRequestSuccess"
}

{
  "transaction_id": "3c2c15a8-3146-4518-9bf2-dd15819bbaa1",
  "customer_id": "testcomp",
  "request_id": "b58491d7-9dd2-4581-91b1-26ecb4eb8568",
  "email_address": "cisco@barbarians.com",
  "full_name": "Cisco Caceres",
  "phone_number": "12066597857",
  "url": "https://bit.ly/3sr6Xg6",
  "request_timestamp": 1610424271524
}