
# Most of these endpoints will be behind a firewall and only to be called directly from the API gateway.
# We will need to secure them nevertheless.

###
# Generate URL for DirectID Connect 
#
@request_id={{$guid}}
# @name income
POST https://dev.barbarians.com/fortifid/DirectID/generateIncomeUrl
content-type: application/json

{
    "full_name": "First Last",
    "email_address": "cisco801@gmail.com",
    "phone_number": "2066597857",
    "request_id": "{{request_id}}",
    "shorten_url": true     
}

###
# DirectID incoming consent webhook
# After a user authorizes access to their account 
POST https://dev.barbarians.com/fortifid/directid/?key=kPgqykCWhR82ePaU4fWOufpcfSW3VqDrR
content-type: application/json

# For some reason this is not working in some environments.
# < ./data/directid_consent.json
# So inlining it.
{
    "consentId": "7c6d77fd-c3e5-4270-e9d4-08d879cd60e9",
    "applicationId": "11e3cccb-5511-4e5f-adb6-e6ec82081f08",
    "customerReference": "Test1123",
    "providerAuthentication": "Error",
    "dataAvailability": null,
    "paymentConfirmation": null,
    "reauthentication": false,
    "errorMessage": null
}

###
# Get request status
#
@income_id = {{income.response.body.$.request_id}}
GET https://dev.barbarians.com/fortifid/directid/?request_id={{income_id}}
content-type: application/json

###
# Service restart
# This will restart the main DirectID service.
# Later we can have a parameter to restart specific services and
# a reload endpoint to just reload the parameters without restarting the service.
GET https://dev.barbarians.com/fortifid/restart

###
# Submit Code #1 (add)
# Just proof of concept
POST https://dev.barbarians.com/fortifid/DirectID/codeSubmit?id=add
content-type: text/plain

'use strict';

return data.a + data.b;

###
# Submit Code #2 (subtract)
# Just proof of concept
POST https://dev.barbarians.com/fortifid/DirectID/codeSubmit?id=subtract
content-type: text/plain

'use strict';

return data.a - data.b;

###
# Run Code #1 (add)
# Just proof of concept
POST https://dev.barbarians.com/fortifid/DirectID/codeRun?id=add
content-type: application/json

{
    "a": 120,
    "b": 50
}

###
# Run Code #1 (subtract)
# Just proof of concept
POST https://dev.barbarians.com/fortifid/DirectID/codeRun?id=subtract
content-type: application/json

{
    "a": 100,
    "b": 50
}

###
# Get EC2 instance meta for auto-configuration use
GET http://169.254.169.254/latest/dynamic/instance-identity/document
