openapi: 3.0.9
info:
  title: FortifID Bank Account Verification
  description: | 
    #### Use the BAV (Bank Account Verification) API to ensure the person has access to the bank account they claim they do.
    <br/>
    <p>All our API products use mutual TLS and require the proper <b>client certificates</b> which are typically different for each environment.</p>    
    <br/>
    <p>
    For sample queries to quickly learn this API:<br/>
    <a href="https://developer.fortifid.com/quickstart/#fid-bav" target="_blank"><img src="https://developer.fortifid.com/images/button-quick-start-guide.png" title="Open Quick Start Guide" alt="Open Quick Start Guide"/></a>
    </p>
    <br/>
    <p>
    This service has a web UI for testing (requires the client certificates to be <a href="https://www.ssl.com/how-to/configuring-client-authentication-certificates-in-web-browsers/" target="_blank">installed</a>):<br/>
    <a href="https://api-uat.fortifid.com/v1/bav/" target="_blank"><img src="https://developer.fortifid.com/images/button-try-it-out.png" title="Try out this API" alt="Try out this API"/></a>
    </p>
    <br/>
    <p>
    Please note that these web UIs are meant only for development and testing.
    </p>
    <br/>
    <br/>
    <br/>
    <br/>
    <h1>Endpoints:</h1>
    <br/>
    <br/>
  termsOfService: https://www.fortifid.com/terms-and-conditions
  contact:
    email: support@fortifid.zendesk.com
  version: 1.0.3
servers:
- url: https://api-uat.fortifid.com/v1
  description: Test server
paths:
  /mfa/generate-url:
    post:
      tags:
      - /bav/generate-url
      summary: Generate a request and optionally send request to phone number.
      operationId: generateUrl
      requestBody:
        description: The request to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestResults'
        400: 
          description: Bad request
          content: {}
        401:
          description: Client certificate is missing or invalid
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found
          content: {}          
        405:
          description: Method not Allowed
          content: {}
        408:
          description: Request Timeout
          content: {}
        422:
          description: Missing or invalid parameter(s)
          content: {}
        429:
          description: Too Many Requests
          content: {}
        500:
          description: Internal Server Error
          content: {}
        501:
          description: Not Implemented
          content: {}   
     
  /bav/check-request/{transaction_id}:
    get:
      tags:
      - /bav/check-request
      summary: Check request status.
      operationId: checkRequest
      parameters:
      - name: transaction_id
        in: path
        description: Transaction ID of BAV to check.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResults'
        400: 
          description: Bad request
          content: {}
        401:
          description: Client certificate is missing or invalid
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found
          content: {}          
        405:
          description: Method not Allowed
          content: {}
        408:
          description: Request Timeout
          content: {}
        422:
          description: Missing or invalid parameter(s)
          content: {}
        429:
          description: Too Many Requests
          content: {}
        500:
          description: Internal Server Error
          content: {}
        501:
          description: Not Implemented
          content: {}   
components:
  schemas:
    Status:
      type: string
      description: Request Status
      enum:  &STATUS [success,sent,not_found,verified,unverified,error]  
    Request:
      required:
      - account_number
      - routing_number
      type: object
      properties:
        phone_number:
          type: string
          description: Phone number to verify. If country code is excluded it will default to +1 (US). Formatting is flexible.
          example: "+18015551213"
        email_address:
          type: string
          example: user@email.com
          description: ""          
        account_number:
          type: string
          description: "User bank account number"
          example: "1111222233331111"
        routing_number:
          type: string
          description: "User bank account routing number"
          example: "011401533"          
        request_reference:
          type: string
          description: This is stored and returned with future requests. Please do not include any PII (Personal Identifiable Information).
          example: abcd1234
        redirect_url:
          type: string
          format: uri
          description: This is stored and returned with future requests.
          example: https://fortifid.com
        sms_text:
          type: string
          description: Custom SMS text body to send to the user.
          default: "Please follow this link to verify your bank account: %URL%"
          example: "Please follow link to verify your bank account: %URL%"
        link_url:
          type: string
          format: uri
          description: The link sent to the user. Can be customized for manual handling.
          default: https://api-uat.fortifid.com/v1/bav/?ref=%ID%
          example: https://custom-verify.com/verify/%ID%          
        expire:
          type: integer
          description: Number of seconds until this transaction expires and will be deleted from the system. Default is 1 week.
          default: 604800
        shorten_url:
          type: boolean
          description: Shortens the link_url sent to the user. Typically adds <30ms to the request.
          default: false
        send:
          type: boolean
          description: Sends the SMS message to the user.
          default: true
    RequestResults:
      type: object
      properties:
        created:
          type: string
          format: date-time
          example: "2021-11-06T17:37:25.863Z"
          description: ISO-8601 date of when the transaction was created.      
        status:
          type: string
          enum: *STATUS        
          example: sent
          description: Current status of the transaction.
        url:
          type: string
          description: URL sent to the user (if send is true).
          example: https://api-uat.fortifid.com/s/H0X2fa          
        transaction_id:
          type: string
          description: Unique transaction ID of this request.
          format: uuid
          example: e7e42ba2-1783-4406-b920-edc681608a2d      
        expires_at:
          type: string
          format: date-time
          example: "2021-11-06T17:37:25.863Z"
          description: ISO-8601 date of when the transaction will be deleted from the system.          
    StatusResults:
      type: object
      properties:
        created:
          type: string
          format: date-time
          example: "2021-11-06T17:37:25.863Z"
          description: ISO-8601 date of when the transaction was created.
        status:
          type: string
          enum: *STATUS        
          description: Current status of the transaction.
          example: verified
        transaction_id:
          type: string
          description: Unique transaction ID of this request.
          format: uuid
          example: e7e42ba2-1783-4406-b920-edc681608a2d      
        completed:
          type: string
          format: date-time
          example: "2021-11-06T17:37:25.863Z" 
          description: ISO-8601 date of when the transaction was completed.
        expires_at:
          type: string
          format: date-time
          example: "2021-11-06T17:37:25.863Z"
          description: ISO-8601 date of when the transaction will be deleted from the system.          
        redirect_url:
          type: string
          format: uri
          description: Saved redirect_url supplied in the original request.
          example: https://fortifid.com
        request_reference:
          type: string
          description: Saved request_reference supplied in the original request.
          example: abcd1234